modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]]
modId="crimsonnbt"
version="${version}"
displayName="CrimsonNBTTags"
displayURL="https://www.curseforge.com/minecraft/mc-mods/crimson-nbt-tags"
authors="§4Crimson_Fluff"
logoFile="logo.png" #optional
credits="\n§bTechnovision§r for his awesome modding YouTube series\n§bTurtyWurty§r for his awesome modding YouTube series" #optional
description=''' A simple mod to show Tags and NBT '''

[[dependencies.crimsonnbt]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
  side="BOTH"
[[dependencies.crimsonnbt]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
